### ISSUE TITLE
Display results, not formulas

### ISSUE THREAD

**Issue by ghost** [zertovitch/excel-writer#1]
I use excel-writer to produce BIFF2 (or BIFF 3 or BIFF 4) documents which I open with Libreoffice Calc and MS Excel 2013

Currently the formulas are displayed.
This is already very good.

I want the results of the formulas to be displayed.

page 216 - 217
[https://www.openoffice.org/sc/excelfileformat.pdf](https://www.openoffice.org/sc/excelfileformat.pdf)

Record WINDOW2, BIFF 2:
0 = Show formula results 1 = Show formulas

Record WINDOW2, BIFF 3-BIFF 5:
0 = Show formula results 1 = Show formulas
Bits 0 Mask= 0001 0 = Show formula results 1 = Show formulas

In
```ada
procedure Write_Window2 is
    begin
      --  5.110 WINDOW2
      case xl.format is
        when BIFF2 =>
          WriteBiff (xl, 16#003E#,
            (0, -- Display formulas, not results
             1, -- Show grid lines
             1, -- Show sheet headers
             Boolean'Pos (xl.frz_panes),
             1  -- Show zero values as zeros, not empty cells
            )
             &
            Intel_16 (0) & -- First visible row
            Intel_16 (0) & -- First visible column
            (1, -- Use automatic grid line colour
             0, 0, 0, 0) -- Grid line RGB colour
          );
        when BIFF3 | BIFF4 =>  --  NB: more options in BIFF8
          WriteBiff (xl, 16#023E#,
            --  http://msdn.microsoft.com/en-us/library/dd947893(v=office.12).aspx
            Intel_16 (   -- Option flags:
              0 *   1 + -- Display formulas, not results
              1 *   2 + -- Show grid lines
              1 *   4 + -- Show sheet headers
              Boolean'Pos (xl.frz_panes)
                *   8 + -- Panes are frozen
              1 *  16 + -- Show zero values as zeros, not empty cells
              1 *  32 + -- Gridlines of the window drawn in the default window foreground color
              0 *  64 + -- Right-to-left mode
              1 * 128 + -- Show outlines (guts ?!)
              0 * 256   -- Frozen, not split
            ) &
            Intel_16 (0) & -- First visible row
            Intel_16 (0) & -- First visible column
            Intel_32 (0)   -- Grid line colour
          );
      end case;
    end Write_Window2;
```

i try 
```ada
          WriteBiff (xl, 16#003E#,
            (1, -- Display formulas, not results
```
I don't get the expected result no (in LibreOffice or MS Excel 2013). 
It may be a problem with LibreOffice (which would read BIFF 2 differently than openoffice ?) ...

**Comment by zertovitch** [comment]
Currently formulas are not implemented, unless you have customized Excel Writer to that aim.
Do you write your formulas as strings?

**Comment by ghost** [comment]
`Currently formulas are not implemented`

ok I understand now that it is on the software side (MS Excel or LibreOffice) that the interpretation of the formula takes place when I perform a small manipulation by hand in the formula which will activate the interpreter to transform the "string" into another form (in inverted Polish notation?) directly usable by the software.
Indeed, this interpreter is not integrated with excel-writer. And I don't know if there is a "bit" in the file produced by excel-writer that would automatically activate the interpreter, on the Ms Excel or LibreOffice side

`Do you write your formulas as strings?`

I use the same method as in `.\test\ew_test.adb`:

 ```ada
declare
        row : constant String := Trim (Integer'Image (power + 2), Both);
      begin
        xl.Put ("= (2^A" & row & ")     - C" & row);
        xl.Put ("=-(2^A" & row & ")     - D" & row);
        xl.Put ("= (2^A" & row & ") - 1 - E" & row);
        xl.Next;
        if power <= 30 then
          xl.Put ("= (2^A" & row & ")     - G" & row);
          xl.Put ("=-(2^A" & row & ")     - H" & row);
          xl.Put ("= (2^A" & row & ") - 1 - I" & row);
        end if;
      end;

```

**Comment by zertovitch** [comment]
So far I did not find an option for the BIFF format that would motivate a spreadsheet program to convert the strings into formulas. I have now added a comment in `ew_test` to reflect the current state. See commit efef953efa561f.

If there is an actual need and use for auto-generated formulas we could consider adding that feature.

It is described in the Chapter 3 of OpenOffice's document. And yes, Reverse-Polish Notation (RPN) is used for storing the formulas.

**Comment by ghost** [comment]
`If there is an actual need and use for auto-generated formulas we could consider adding that feature.`

Thanks, no need. I found a solution that suits me because I have few formulas: I have an xls file with ada that does the sums and another file with the formulas allowing a manual check if necessary to verify that all the data are well transcribed in the excel file.
  
This is sufficient for me and does not require any additional functionality.
