### ISSUE TITLE
when Define_format total number exceed 62, execution error occurs.  

### ISSUE THREAD

**Issue by jzh-softimp** [zertovitch/excel-writer#2]
When I define define_format exceed 44, the execution error occurs.
error message: 
"raised CONSTRAINT_ERROR:
excel_out.adb:700 index check failed"

**Comment by jzh-softimp** [comment]
the last xl.xfs value is 63, then the error comes

**Comment by jzh-softimp** [comment]
subtype XF_Range is Integer range 0 .. 62; -- after 62 we'd need to use an IXFE (5.62)
  max_font  : constant := 62;
  max_format : constant := 62;

**Comment by zertovitch** [comment]
Now there is an explicit raise, with (hopefully) a clearer message: "raised EXCEL_OUT.FORMAT_OUT_OF_RANGE : Too many formats defined, maximum number of formats (including a few pre-defined) is 63".
```
with Excel_Out;

procedure XL_Test is
  use Excel_Out;
  xl : Excel_Out_File;
  fmt : array (1 .. 100) of  Format_type;
begin
  xl.Create ("Small.xls");
  for i in 1 .. 100 loop
    xl.Define_format (xl.Default_font, general, fmt (i));
  end loop;
  xl.Close;
end XL_Test;

```
Note that a larger number of formats is possible, but this needs a bit of development (cf. the IXFE record mentioned).
As a side note, it would be a good idea to add a similar check for maximum fonts and number formats.
